[build]
  command = "npm run build"
  publish = "out"

# Remove the Next.js plugin since we're using static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs" 

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 